# Generated by Django 4.2.3 on 2023-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='images/'),
        ),
    ]
